### ISSUE TITLE
motor communication

### ISSUE THREAD

**Issue by RoboCary-cpu** [bit-bots/bitbots_lowlevel#95]
I have a problem when i try to communicate with robotis servo on jetson NX.
It turns to have great loss, when I send the message in the speed of 100HZ using dynaxiel SDK.
However, it works well in my computer.

**Comment by Flova** [comment]
There was some USB setting that enabled some low latency mode iirc. It could be that. @SammyRamone knows Mord about this.

**Comment by Flova** [comment]
http://doku.bit-bots.de/meta/manual/tutorials/lowlevel.html?highlight=usb

**Comment by Flova** [comment]
There are some insights regarding this setup.

**Comment by SammyRamone** [comment]
As @Flova pointed out above, did you set these [settings](http://doku.bit-bots.de/meta/manual/tutorials/lowlevel.html?highlight=usb#kernel)?
If you did and the problem still remains, you will need to use a logic analyzer to see if it is due to timeouts, corrupted packages or latency introduced by the jetson.

**Comment by RoboCary-cpu** [comment]
OK，I have fixed the problem.
I use the rospy.spin to replace while true in the communication node, then it wroks!
